### PR TITLE
fix: complete on selection changed

### PR DESCRIPTION
**Pull request by philippfromme**
Related to https://github.com/camunda/camunda-modeler/issues/2961

### CODE REVIEW

**Comment by marstamm** [comment]
I'm wondering if the end condition is a concern for direct-editing. In the past, we captured these events and triggered the complete it in bpmn-js:

https://github.com/bpmn-io/bpmn-js/blob/05b7f775b0a468b0562ca9d12d49220ff1fe843e/lib/features/label-editing/LabelEditingProvider.js#L45-L58

**Comment by nikku** [comment]
Good point. You could argue we should keep it this way, as only bpmn-js is aware of the full context.

**Review by nikku — CHANGES_REQUESTED** [review]
Should move into integrating libraries, cf. https://github.com/bpmn-io/diagram-js-direct-editing/pull/24#issuecomment-1128555182.

**Comment by philippfromme** [comment]
I chose this project to avoid having to configure it both in bpmn-js and dmn-js. But okay, I'll move it.

**Pull request closed without merging**
